spring:
  datasource:
    druid:
      password: root
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/my_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_uuid
  mapper-locations:classpath:mapper/*.xml
